baseurl = "biface.co/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "biface"
theme = "rock"
disableLanguages = ["en"]


[params]
    logo = "svg/logo-mainsrouges.svg"



[languages]
  [languages.fr]
    title = "biface"
    subtitle = "Design et contenus numériques "
    description="On s’adapte à votre univers et à vos objectifs pour concevoir des outils fonctionnels et impactants."
    weight = 1
    languageName = "Fr"